steps:
- name: 'golang:1.11.1-stretch'
  entrypoint: 'go'
  args: ['build', '.']
  env: ['GO111MODULE=on']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/insert-tweet-hash-key-dep
    - insert-tweet-hash-key-dep=gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/insert-tweet-dep
    - insert-tweet-dep=gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/list-tweet-dep
    - list-tweet-dep=gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/insert-tweet-mini-dep
    - insert-tweet-mini-dep=gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/update-tweet-dep
    - update-tweet-dep=gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo'
images: ['gcr.io/$PROJECT_ID/sinmetal/alminium_spanner/$BRANCH_NAME:$COMMIT_SHA']