apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: insert-tweet-dep
  name: insert-tweet-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: insert-tweet-dep
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/sinmetal/alminium_spanner
        name: insert-tweet-dep
        resources:
          limits:
            cpu: "8"
          requests:
            cpu: "4"
        args:
        - -cpus
        - "2"
        envFrom:
          - configMapRef:
              name: config
          - configMapRef:
              name: insert-tweet-config